### ISSUE TITLE
Send goes straight to the delegated object

### ISSUE THREAD

**Issue by eljojo** [stevenharman/dumb_delegator#9]
Hi, I just discovered this gem and it looks very interesting, I found a small bug, though.

If I call `send` on a DumbDelegator object, it goes straight to the delegated object.

``` ruby
>> coffee = Coffee.new
=> #<Coffee:0x007fad18dc6550>
>> Milk.new(coffee).cost
=> 2.4
>> Milk.new(coffee).send(:cost)
=> 2
>>
```

Something like this does the job, but I don't know if it's ideal:

``` ruby
def send(*args)
  if self.respond_to?(args.first) then
    self.__send__(*args)
  else
    super
  end
end
```

**Comment by feliperaul** [comment]
@stevenharman Thanks for this nice gem.

However, I just want to chip in that I also got bitten by this. I had never used `__send__` before, I had always used `send` , and this bug was really hard to track down because I didn't understand why the decorator wasn't responding to a `#send` if the method was clearly defined there.

**Comment by feliperaul** [comment]
I ended up hitting comment prematurely :)

My humble suggestions would be:

1. Make the delegator also respond to send (I think it wouldn't break anyones expectation, and you can always override `send` in the delegator if you want to send it to the delegated object directly); I strongly favor this one :)

2. Add a configuration for this on the gem ?

3. If current behavior is kept, add very clear documentation about this behavior.

**Comment by stevenharman** [comment]
Hello @feliperaul! Thanks for the feedback. And sorry that you were tripped up by this.

I'll address your suggestions in order:

> 1. Make the delegator also respond to send (I think it wouldn't break anyones expectation, and you can always override send in the delegator if you want to send it to the delegated object directly);

`DumbDelegator` not responding to `send` is by design. With the goal of being a really stripped down delegator, we believe that [Ruby's `__send__` was sufficient](https://github.com/stevenharman/dumb_delegator/commit/6eabf36e689193daec2cf769037437b89cca5bd1) for the delegator to implement. The `DumbDelegator` object explicitly inherits from Ruby's `BasicObject` object, rather than the default `Object`. The `#send` method is not defined on `BasicObject`, but rather by `Object`.

> 2. Add a configuration for this 

I understand the desire, but the tradeoff of increased complexity for that configuration is not worth it in my experience.

> 3. If current behavior is kept, add very clear documentation about this behavior.

💯 Totally agree. This could certainly be called out more clearly in the docs. Would you like to give it a go?
